import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class ChopStick extends ReentrantLock{
	
	private static final long serialVersionUID = 1L;	// default serial version generated by Java
	private final int id;
	Lock myLock = new ReentrantLock();
	
	public ChopStick(int id) {
		this.id = id;
	}
	
	//get method 
		public int getId(){
			return id;
		}
}
